name: Create a configmap
on:
  push:
    branches:
      - master
      - main

jobs:
  createFile:
    name: Create a k8s configmap file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: HasanBilal133/create-a-k8s-configmap-action@master
        with:
          path: 'k8s'
          name: 'backend-configmap'
          params: |
            PARAM1: VALUE1
            PARAM2: VALUE2
