name: Create a configmap
on:
  push:
    branches:
      - master
      - main

jobs:
  createFile:
    name: Create A File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: HasanBilal133/create-a-k8s-configmap-action@master
        with:
          path: 'k8s'
          name: 'backend-configmap.yaml'
          params: |
            - PARAM1: VALUE1
            - PARAM2: VALUE2
      - name: Commit files 
        run: |
          git config --local user.email "126247712+testTTL11112@users.noreply.github.com"
          git config --local user.name "GitHub Action test"
          git add .
          git commit -m "Add changes"
          git config --local --unset-all "http.https://github.com/.extraheader"
          git push https://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@github.com/testTTL11112/test-create-configmap.git

